version: '3'

services:
  web:
    image: dtr1.d.demok.it/prod/flask-demo
    deploy:
        replicas: 3
        placement:
            constraints:
              - node.role != manager
              - node.platform.os == linux
    ports:
      - "8000:5000"
