apiVersion: v1
kind: Namespace
metadata:
  name: flask-demo
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: flask-demo
  labels:
    app: flask-demo-web
spec:
  ports:
    - port: 8081
      targetPort: 5000
      name: web
  selector:
    app: flask-demo-web
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: flask-demo
  labels:
    app: flask-demo-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-demo-web
    spec:
      containers:
      - name: web
        image: dtr1.d.demok.it/prod/flask-demo
        ports:
        - containerPort: 5000
          name: flask-demo-web
